//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v2alpha1

import runtime "k8s.io/apimachinery/pkg/runtime"

// DeepCopyObject implements runtime.Object.
func (in *HardwareConfig) DeepCopyObject() runtime.Object {
	out := new(HardwareConfig)
	in.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *HardwareConfig) DeepCopyInto(out *HardwareConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopyObject implements runtime.Object.
func (in *HardwareConfigList) DeepCopyObject() runtime.Object {
	out := new(HardwareConfigList)
	in.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *HardwareConfigList) DeepCopyInto(out *HardwareConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)

	if in.Items != nil {
		out.Items = make([]HardwareConfig, len(in.Items))

		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *HardwareConfigSpec) DeepCopyInto(out *HardwareConfigSpec) {
	*out = *in
	in.Profile.DeepCopyInto(&out.Profile)
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *HardwareProfile) DeepCopyInto(out *HardwareProfile) {
	*out = *in

	if in.ClockChain != nil {
		out.ClockChain = new(ClockChain)
		in.ClockChain.DeepCopyInto(out.ClockChain)
	}
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ClockChain) DeepCopyInto(out *ClockChain) {
	*out = *in

	if in.Structure != nil {
		out.Structure = make([]Subsystem, len(in.Structure))

		for i := range in.Structure {
			in.Structure[i].DeepCopyInto(&out.Structure[i])
		}
	}
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *Subsystem) DeepCopyInto(out *Subsystem) {
	*out = *in
	in.DPLL.DeepCopyInto(&out.DPLL)
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *DPLL) DeepCopyInto(out *DPLL) {
	*out = *in

	if in.HoldoverParameters != nil {
		out.HoldoverParameters = new(HoldoverParameters)
		*out.HoldoverParameters = *in.HoldoverParameters
	}
}
