name: Integration Testing (PRs)

on:
  workflow_call:
    inputs:
      branch:
        description: Branch to run on
        required: true
        default: main
        type: string
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  integration-k8s:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    env:
      SHELL: /bin/bash
      KUBECONFIG: '/home/runner/.kube/config'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch || github.sha }}

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Setup cluster (k8s)
        uses: palmsoftware/quick-k8s@v0.0.40
        with:
          waitForPodsReady: true

      - name: Run integration tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 90
          max_attempts: 3
          command: make integration-test
