name: Test Incoming Changes

on:
  workflow_call:
    inputs:
      branch:
        description: Branch to run on
        required: true
        default: main
        type: string

  workflow_dispatch:

  push:

  pull_request:
    branches:
      - main
      - 'release-\d.\d\d'

jobs:
  lint:
    runs-on: ubuntu-24.04
    env:
      SHELL: /bin/bash

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
            ref: ${{ inputs.branch || github.sha }}

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Run lint
        run: make lint

  test:
    runs-on: ubuntu-24.04
    env:
      SHELL: /bin/bash

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          ref: ${{ inputs.branch || github.sha }}

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Run unit tests
        run: make test

      - name: Generate test coverage
        run: go test ./pkg/... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

      - name: Check test coverage
        uses: vladopajic/go-test-coverage@5f3508324fc185e82048a2861f8bdd3d83db133b # v2
        with:
          # Configure action using config file (option 1)
          config: ./.testcoverage.yml
          git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
          git-branch: badges
