name: Test Incoming Changes

on:
  workflow_call:
    inputs:
      branch:
        description: Branch to run on
        required: true
        default: main
        type: string

  workflow_dispatch:

  push:

  pull_request:
    branches:
      - main
      - 'release-\d.\d\d'

jobs:
  lint:
    runs-on: ubuntu-24.04
    env:
      SHELL: /bin/bash

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
            ref: ${{ inputs.branch || github.sha }}

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Run lint
        run: make lint

  test:
    runs-on: ubuntu-24.04
    env:
      SHELL: /bin/bash

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ inputs.branch || github.sha }}

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Run unit tests
        run: make test

      - name: Generate test coverage
        run: go test ./pkg/... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

      - name: Check test coverage
        uses: vladopajic/go-test-coverage@a93b868a4cbcbf18dc3781650fad241f0020e609 # v2
        with:
          # Configure action using config file (option 1)
          config: ./.testcoverage.yml
          git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
          git-branch: badges
