name: Verify lib-sync is up to date

on:
  pull_request:
    branches:
      - main
      - 'release-[0-9].[0-9][0-9]'
    paths:
      - 'internal/sync/configs/**'
      - 'pkg/schemes/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify-lib-sync:
    runs-on: ubuntu-latest
    env:
      SHELL: /bin/bash

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Run lib-sync
        run: make lib-sync

      - name: Ensure vet passes
        run: make vet
